version: 2

run:
  timeout: 5m
  tests: false

# Output format to generate checkstyle report (used by CI)
output:
  formats:
    checkstyle:
      path: codequality/golangci-lint-report.xml
    text:
      path: stdout
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      # local-prefixes: github.com/boxboxjason/sonarqube-client-go
    gofmt:
      simplify: true

linters:
  default: all
  disable:
    - depguard
    - lll
    - err113
    - wsl
  settings:
    govet:
      enable-all: true
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/boxboxjason)
      skip-generated: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
