run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - structcheck # deprecated
    - varcheck # deprecated
    - deadcode # deprecated

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/boxboxjason/sonarqube-client-go

issues:
  exclude-rules:
    # Ignore long lines in generated code
    - path: generated_static_file_const\.go
      linters:
        - lll
    # Ignore complexity in test files
    - path: _test\.go
      linters:
        - cyclop
        - funlen
    # Ignore unused parameters in test helper functions
    - path: pkg/testutil/
      linters:
        - unused
  max-issues-per-linter: 50
  max-same-issues: 3
