// Package api defines the structure of the SonarQube Web API.
// Generated by https://quicktype.io
//
//nolint:revive
package api

// API represents the root of the SonarQube Web API definition.
type API struct {
	WebServices []WebService `json:"webServices"`
}

// WebService represents a SonarQube web service.
type WebService struct {
	Path        string   `json:"path"`
	Description string   `json:"description,omitempty"`
	Since       string   `json:"since,omitempty"`
	Actions     []Action `json:"actions"`
}

// Action represents an action within a web service.
type Action struct {
	Key                string      `json:"key"`
	Description        string      `json:"description"`
	Since              string      `json:"since"`
	DeprecatedSince    string      `json:"deprecatedSince,omitempty"`
	ResponseType       string      `json:"responseType,omitempty"`
	Changelog          []Changelog `json:"changelog"`
	Params             []Param     `json:"params"`
	Internal           bool        `json:"internal"`
	Post               bool        `json:"post"`
	HasResponseExample bool        `json:"hasResponseExample"`
}

// Changelog represents a change in the API.
type Changelog struct {
	Description string `json:"description"`
	Version     string `json:"version"`
}

// Param represents a parameter for an action.
type Param struct {
	DeprecatedKeySince string   `json:"deprecatedKeySince,omitempty"`
	DefaultValue       string   `json:"defaultValue,omitempty"`
	Since              string   `json:"since,omitempty"`
	DeprecatedKey      string   `json:"deprecatedKey,omitempty"`
	ExampleValue       string   `json:"exampleValue,omitempty"`
	DeprecatedSince    string   `json:"deprecatedSince,omitempty"`
	Description        string   `json:"description,omitempty"`
	Key                string   `json:"key"`
	PossibleValues     []string `json:"possibleValues"`
	MaximumValue       int64    `json:"maximumValue,omitempty"`
	MinimumLength      int64    `json:"minimumLength,omitempty"`
	MaxValuesAllowed   int64    `json:"maxValuesAllowed,omitempty"`
	MaximumLength      int64    `json:"maximumLength,omitempty"`
	Internal           bool     `json:"internal"`
	Required           bool     `json:"required"`
}
