// Code generated by `make generate`. DO NOT EDIT.

// Get JAR files and referentials for batch
package sonargo

import "net/http"

type HService struct {
	client *Client
}

type HProjectObject struct {
	FileDataByModuleAndPath HProjectObject_sub3 `json:"fileDataByModuleAndPath,omitempty"`
	LastAnalysisDate        int64               `json:"lastAnalysisDate,omitempty"`
	Timestamp               int64               `json:"timestamp,omitempty"`
}

type HProjectObject_sub3 struct {
	Com_sonarsource_java_markdown HProjectObject_sub2 `json:"com.sonarsource:java-markdown,omitempty"`
}

type HProjectObject_sub1 struct {
	Hash     string `json:"hash,omitempty"`
	Revision string `json:"revision,omitempty"`
}

type HProjectObject_sub2 struct {
	Src_main_java_com_sonarsource_markdown_Element_java                  HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/Element.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_ElementType_java              HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/ElementType.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_GrammarDefinition_java        HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/GrammarDefinition.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_Parser_java                   HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/Parser.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_impl_ElementImpl_java         HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/impl/ElementImpl.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_impl_Rule_java                HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/impl/Rule.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_impl_RuleBuilder_java         HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/impl/RuleBuilder.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_mark_Mark_java                HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/mark/Mark.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_mark_MarkHighlighter_java     HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/mark/MarkHighlighter.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_mark_MarkType_java            HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/mark/MarkType.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_mark_RegexMarker_java         HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/mark/RegexMarker.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_sq_HtmlGenerator_java         HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/sq/HtmlGenerator.java,omitempty"`
	Src_main_java_com_sonarsource_markdown_sq_WikiParser_java            HProjectObject_sub1 `json:"src/main/java/com/sonarsource/markdown/sq/WikiParser.java,omitempty"`
	Src_test_java_com_sonarsource_markdown_BasicMarkdownParser_java      HProjectObject_sub1 `json:"src/test/java/com/sonarsource/markdown/BasicMarkdownParser.java,omitempty"`
	Src_test_java_com_sonarsource_markdown_BasicMarkdownParserTest_java  HProjectObject_sub1 `json:"src/test/java/com/sonarsource/markdown/BasicMarkdownParserTest.java,omitempty"`
	Src_test_java_com_sonarsource_markdown_GrammarDefinitionTest_java    HProjectObject_sub1 `json:"src/test/java/com/sonarsource/markdown/GrammarDefinitionTest.java,omitempty"`
	Src_test_java_com_sonarsource_markdown_impl_ElementImplTest_java     HProjectObject_sub1 `json:"src/test/java/com/sonarsource/markdown/impl/ElementImplTest.java,omitempty"`
	Src_test_java_com_sonarsource_markdown_impl_RuleBuilderTest_java     HProjectObject_sub1 `json:"src/test/java/com/sonarsource/markdown/impl/RuleBuilderTest.java,omitempty"`
	Src_test_java_com_sonarsource_markdown_mark_MarkHighlighterTest_java HProjectObject_sub1 `json:"src/test/java/com/sonarsource/markdown/mark/MarkHighlighterTest.java,omitempty"`
	Src_test_java_com_sonarsource_markdown_sq_HtmlDecoratorTest_java     HProjectObject_sub1 `json:"src/test/java/com/sonarsource/markdown/sq/HtmlDecoratorTest.java,omitempty"`
	Src_test_java_com_sonarsource_markdown_sq_WikiParserTest_java        HProjectObject_sub1 `json:"src/test/java/com/sonarsource/markdown/sq/WikiParserTest.java,omitempty"`
}

type HFileOption struct {
	Name string `url:"name,omitempty"` // Description:"File name",ExampleValue:"batch-library-2.3.jar"
}

// File Download a JAR file listed in the index (see batch/index)
func (s *HService) File(opt *HFileOption) (v *string, resp *http.Response, err error) {
	err = s.ValidateFileOpt(opt)
	if err != nil {
		return
	}
	req, err := s.client.NewRequest("GET", "h/file", opt)
	if err != nil {
		return
	}
	v = new(string)
	resp, err = s.client.Do(req, v)
	if err != nil {
		return nil, resp, err
	}
	return
}

// Index List the JAR files to be downloaded by scanners
func (s *HService) Index() (v *string, resp *http.Response, err error) {
	req, err := s.client.NewRequest("GET", "h/index", nil)
	if err != nil {
		return
	}
	v = new(string)
	resp, err = s.client.Do(req, v)
	if err != nil {
		return nil, resp, err
	}
	return
}

type HProjectOption struct {
	Branch      string `url:"branch,omitempty"`      // Description:"Branch key",ExampleValue:"feature/my_branch"
	Key         string `url:"key,omitempty"`         // Description:"Project key",ExampleValue:"my_project"
	Profile     string `url:"profile,omitempty"`     // Description:"Profile name",ExampleValue:"SonarQube Way"
	PullRequest string `url:"pullRequest,omitempty"` // Description:"Pull request id",ExampleValue:"5461"
}

// Project Return project repository
func (s *HService) Project(opt *HProjectOption) (v *HProjectObject, resp *http.Response, err error) {
	err = s.ValidateProjectOpt(opt)
	if err != nil {
		return
	}
	req, err := s.client.NewRequest("GET", "h/project", opt)
	if err != nil {
		return
	}
	v = new(HProjectObject)
	resp, err = s.client.Do(req, v)
	if err != nil {
		return nil, resp, err
	}
	return
}
