// Code generated by `make generate`. DO NOT EDIT.

package sonargo

func (s *HService) ValidateFileOpt(opt *HFileOption) error {
	return nil
}
func (s *HService) ValidateProjectOpt(opt *HProjectOption) error {
	return nil
}
