// Package static provides functionality to generate static files.
package static

import (
	"fmt"
	"os"

	gen "github.com/dave/jennifer/jen"
)

// ConstFileName is the name of the generated file containing static constants.
const ConstFileName = "zz_static_file_const.go"

var (
	//nolint:gochecknoglobals
	staticFiles = [...]string{"sonarqube.go.temp", "client_util.go.temp", "suite_test.go.temp"}
	//nolint:gochecknoglobals
	staticName = [...]string{"SonarqubeConst", "WebClientConst", "TestSuiteConst"}
)

// GenerateStaticFiles generates the static files.
func GenerateStaticFiles(navDir string, outputPath string) error {
	file := gen.NewFile("generate")
	file.HeaderComment("Code generated by `make generate`. DO NOT EDIT.")

	for index, name := range staticFiles {
		content, err := LoadStaticFile(navDir + "/" + name)
		if err != nil {
			return fmt.Errorf("failed to load static file %s: %w", name, err)
		}

		file.Const().Id(staticName[index]).Op("=").Lit(content)
	}

	err := file.Save(outputPath + "/" + ConstFileName)
	if err != nil {
		return fmt.Errorf("failed to save file: %w", err)
	}

	return nil
}

// LoadStaticFile loads a static file from the given path.
func LoadStaticFile(path string) (string, error) {
	//nolint:gosec
	bytes, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read file: %w", err)
	}

	return string(bytes), nil
}
