// Code generated by `make generate`. DO NOT EDIT.

package main

import (
	"fmt"
	. "github.com/boxboxjason/sonarqube-client-go/sonar"
	spew "github.com/davecgh/go-spew/spew"
	"os"
)

var client *Client

func init() {
	sonarURL := os.Getenv("SONAR_URL")
	if sonarURL == "" {
		fmt.Println("Sonar URL has not been set")
		os.Exit(1)
	}
	c, err := NewClient(sonarURL+"/api", "admin", "admin")
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	client = c

}

// You should MANUALLY add the test func in here
func main() {
	return
}

// CeTaskTypesjenFunc testing List available task types
func CeTaskTypesjenFunc() {
	v, resp, err := client.Ce.TaskTypes()
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// CeWorkerCountjenFunc testing Return number of Compute Engine workers.<br/>Requires the system administration permission
func CeWorkerCountjenFunc() {
	v, resp, err := client.Ce.WorkerCount()
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// ComponentsSearchProjectsjenFunc testing Search for projects
func ComponentsSearchProjectsjenFunc() {
	opt := &ComponentsSearchProjectsOption{
		Asc:    "true",
		F:      "analysisDate",
		Facets: "coverage",
		P:      "1",
		Ps:     "100",
		S:      "name",
	}
	v, resp, err := client.Components.SearchProjects(opt)
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// ComponentsSuggestionsjenFunc testing Internal WS for the top-right search engine. The result will contain component search results, grouped by their qualifiers.<p>Each result contains:<ul><li>the component key</li><li>the component's name (unescaped)</li><li>optionally a display name, which puts emphasis to matching characters (this text contains html tags and parts of the html-escaped name)</li></ul>
func ComponentsSuggestionsjenFunc() {
	opt := &ComponentsSuggestionsOption{
		More: "TRK",
		S:    "name",
	}
	v, resp, err := client.Components.Suggestions(opt)
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// MeasuresSearchjenFunc testing Search for project measures ordered by project names.<br>At most 100 projects can be provided.<br>Returns the projects with the 'Browse' permission.
func MeasuresSearchjenFunc() {
	opt := &MeasuresSearchOption{
		MetricKeys:  "coverage",
		ProjectKeys: "test-project",
	}
	v, resp, err := client.Measures.Search(opt)
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// NavigationMarketplacejenFunc testing Provide data to prefill license request forms: the server ID and the total number of lines of code.
func NavigationMarketplacejenFunc() {
	v, resp, err := client.Navigation.Marketplace()
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// NavigationSettingsjenFunc testing Get configuration information for the settings page:<ul>  <li>List plugin-contributed pages</li>  <li>Show update center (or not)</li></ul>
func NavigationSettingsjenFunc() {
	v, resp, err := client.Navigation.Settings()
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// ProjectBranchesSetAutomaticDeletionProtectionjenFunc testing Protect a specific branch from automatic deletion. Protection can't be disabled for the main branch.<br/>Requires 'Administer' permission on the specified project or application.
func ProjectBranchesSetAutomaticDeletionProtectionjenFunc() {
	opt := &ProjectBranchesSetAutomaticDeletionProtectionOption{
		Branch:  "main",
		Project: "test-project",
		Value:   "true",
	}
	resp, err := client.ProjectBranches.SetAutomaticDeletionProtection(opt)
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
}

// ProjectBranchesSetMainjenFunc testing Allow to set a new main branch.<br/>. Caution, only applicable on projects.<br>Requires 'Administer' rights on the specified project or application.
func ProjectBranchesSetMainjenFunc() {
	opt := &ProjectBranchesSetMainOption{
		Branch:  "main",
		Project: "test-project",
	}
	resp, err := client.ProjectBranches.SetMain(opt)
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
}

// QualityprofilesImportersjenFunc testing List supported importers.
func QualityprofilesImportersjenFunc() {
	v, resp, err := client.Qualityprofiles.Importers()
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// SettingsLoginMessagejenFunc testing Returns the formatted login message, set to the 'sonar.login.message' property.
func SettingsLoginMessagejenFunc() {
	v, resp, err := client.Settings.LoginMessage()
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}

// UsersUpdatejenFunc testing Update a user.<br/>Requires Administer System permission
func UsersUpdatejenFunc() {
	opt := &UsersUpdateOption{
		Email: "test@example.com",
		Login: "test-user",
		Name:  "test-name",
	}
	v, resp, err := client.Users.Update(opt)
	if err != nil {
		fmt.Println(err.jen.Error())
		os.Exit(1)
	}
	fmt.Println(resp.StatusCode)
	spew.Dump(v)
}
