// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test CountBinding - action is dangerous/disruptive

	// SKIPPED: Test CreateAzure - action is dangerous/disruptive

	// SKIPPED: Test CreateBitbucket - action is dangerous/disruptive

	// SKIPPED: Test CreateBitbucketcloud - action is dangerous/disruptive

	// SKIPPED: Test CreateGithub - action is dangerous/disruptive

	// SKIPPED: Test CreateGitlab - action is dangerous/disruptive

	// SKIPPED: Test Delete - action is dangerous/disruptive

	// SKIPPED: Test GetBinding - action is dangerous/disruptive

	// SKIPPED: Test List - action is dangerous/disruptive

	// SKIPPED: Test ListDefinitions - action is dangerous/disruptive

	// SKIPPED: Test UpdateAzure - action is dangerous/disruptive

	// SKIPPED: Test UpdateBitbucket - action is dangerous/disruptive

	// SKIPPED: Test UpdateBitbucketcloud - action is dangerous/disruptive

	// SKIPPED: Test UpdateGithub - action is dangerous/disruptive

	// SKIPPED: Test UpdateGitlab - action is dangerous/disruptive

	// SKIPPED: Test Validate - action is dangerous/disruptive
})
