// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test CheckPat - action is dangerous/disruptive

	// SKIPPED: Test GetGithubClientId - action is dangerous/disruptive

	// SKIPPED: Test ImportAzureProject - action is dangerous/disruptive

	// SKIPPED: Test ImportBitbucketcloudRepo - action is dangerous/disruptive

	// SKIPPED: Test ImportBitbucketserverProject - action is dangerous/disruptive

	// SKIPPED: Test ImportGithubProject - action is dangerous/disruptive

	// SKIPPED: Test ImportGitlabProject - action is dangerous/disruptive

	// SKIPPED: Test ListAzureProjects - action is dangerous/disruptive

	// SKIPPED: Test ListBitbucketserverProjects - action is dangerous/disruptive

	// SKIPPED: Test ListGithubOrganizations - action is dangerous/disruptive

	// SKIPPED: Test ListGithubRepositories - action is dangerous/disruptive

	// SKIPPED: Test SearchAzureRepos - action is dangerous/disruptive

	// SKIPPED: Test SearchBitbucketcloudRepos - action is dangerous/disruptive

	// SKIPPED: Test SearchBitbucketserverRepos - action is dangerous/disruptive

	// SKIPPED: Test SearchGitlabRepos - action is dangerous/disruptive

	// SKIPPED: Test SetPat - action is dangerous/disruptive
})
