// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	ginkgo "github.com/onsi/ginkgo"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test Activity - action is dangerous/disruptive

	// SKIPPED: Test ActivityStatus - action is dangerous/disruptive

	// SKIPPED: Test AnalysisStatus - action is dangerous/disruptive

	// SKIPPED: Test Cancel - action is dangerous/disruptive

	// SKIPPED: Test CancelAll - action is dangerous/disruptive

	// SKIPPED: Test Component - action is dangerous/disruptive

	// SKIPPED: Test DismissAnalysisWarning - action is dangerous/disruptive

	// SKIPPED: Test IndexationStatus - action is dangerous/disruptive

	// SKIPPED: Test Info - action is dangerous/disruptive

	// SKIPPED: Test Pause - action is dangerous/disruptive

	// SKIPPED: Test Resume - action is dangerous/disruptive

	// SKIPPED: Test Submit - action is dangerous/disruptive

	// SKIPPED: Test Task - action is dangerous/disruptive
	ginkgo.Describe("Test TaskTypes in api/ce", func() {
		ginkgo.It("Should be ok", func() {
			v, resp, err := client.Ce.TaskTypes()
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})
	ginkgo.Describe("Test WorkerCount in api/ce", func() {
		ginkgo.It("Should be ok", func() {
			v, resp, err := client.Ce.WorkerCount()
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})
})
