// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	sonar "github.com/boxboxjason/sonarqube-client-go/sonar"
	ginkgo "github.com/onsi/ginkgo"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test App - action is dangerous/disruptive

	// SKIPPED: Test Search - action is dangerous/disruptive
	ginkgo.Describe("Test SearchProjects in api/components", func() {
		ginkgo.It("Should be ok", func() {
			opt := &sonar.ComponentsSearchProjectsOption{
				Asc:    "true",
				F:      "analysisDate",
				Facets: "coverage",
				P:      "1",
				Ps:     "100",
				S:      "name",
			}
			v, resp, err := client.Components.SearchProjects(opt)
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})

	// SKIPPED: Test Show - action is dangerous/disruptive
	ginkgo.Describe("Test Suggestions in api/components", func() {
		ginkgo.It("Should be ok", func() {
			opt := &sonar.ComponentsSuggestionsOption{
				More: "TRK",
				S:    "name",
			}
			v, resp, err := client.Components.Suggestions(opt)
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})

	// SKIPPED: Test Tree - action is dangerous/disruptive
})
