// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test AddComment - action is dangerous/disruptive

	// SKIPPED: Test Assign - action is dangerous/disruptive

	// SKIPPED: Test ChangeStatus - action is dangerous/disruptive

	// SKIPPED: Test DeleteComment - action is dangerous/disruptive

	// SKIPPED: Test EditComment - action is dangerous/disruptive

	// SKIPPED: Test List - action is dangerous/disruptive

	// SKIPPED: Test Pull - action is dangerous/disruptive

	// SKIPPED: Test Search - action is dangerous/disruptive

	// SKIPPED: Test Show - action is dangerous/disruptive
})
