// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test AddComment - action is dangerous/disruptive

	// SKIPPED: Test AnticipatedTransitions - action is dangerous/disruptive

	// SKIPPED: Test Assign - action is dangerous/disruptive

	// SKIPPED: Test Authors - action is dangerous/disruptive

	// SKIPPED: Test BulkChange - action is dangerous/disruptive

	// SKIPPED: Test Changelog - action is dangerous/disruptive

	// SKIPPED: Test ComponentTags - action is dangerous/disruptive

	// SKIPPED: Test DeleteComment - action is dangerous/disruptive

	// SKIPPED: Test DoTransition - action is dangerous/disruptive

	// SKIPPED: Test EditComment - action is dangerous/disruptive

	// SKIPPED: Test List - action is dangerous/disruptive

	// SKIPPED: Test Pull - action is dangerous/disruptive

	// SKIPPED: Test PullTaint - action is dangerous/disruptive

	// SKIPPED: Test Reindex - action is dangerous/disruptive

	// SKIPPED: Test Search - action is dangerous/disruptive

	// SKIPPED: Test SetSeverity - action is dangerous/disruptive

	// SKIPPED: Test SetTags - action is dangerous/disruptive

	// SKIPPED: Test SetType - action is dangerous/disruptive

	// SKIPPED: Test Tags - action is dangerous/disruptive
})
