// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	sonar "github.com/boxboxjason/sonarqube-client-go/sonar"
	ginkgo "github.com/onsi/ginkgo"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test Component - action is dangerous/disruptive

	// SKIPPED: Test ComponentTree - action is dangerous/disruptive
	ginkgo.Describe("Test Search in api/measures", func() {
		ginkgo.It("Should be ok", func() {
			opt := &sonar.MeasuresSearchOption{
				MetricKeys:  "coverage",
				ProjectKeys: "test-project",
			}
			v, resp, err := client.Measures.Search(opt)
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})

	// SKIPPED: Test SearchHistory - action is dangerous/disruptive
})
