// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	ginkgo "github.com/onsi/ginkgo"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test Component - action is dangerous/disruptive

	// SKIPPED: Test Global - action is dangerous/disruptive
	ginkgo.Describe("Test Marketplace in api/navigation", func() {
		ginkgo.It("Should be ok", func() {
			v, resp, err := client.Navigation.Marketplace()
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})
	ginkgo.Describe("Test Settings in api/navigation", func() {
		ginkgo.It("Should be ok", func() {
			v, resp, err := client.Navigation.Settings()
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})
})
