// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test AddGroup - action is dangerous/disruptive

	// SKIPPED: Test AddGroupToTemplate - action is dangerous/disruptive

	// SKIPPED: Test AddProjectCreatorToTemplate - action is dangerous/disruptive

	// SKIPPED: Test AddUser - action is dangerous/disruptive

	// SKIPPED: Test AddUserToTemplate - action is dangerous/disruptive

	// SKIPPED: Test ApplyTemplate - action is dangerous/disruptive

	// SKIPPED: Test BulkApplyTemplate - action is dangerous/disruptive

	// SKIPPED: Test CreateTemplate - action is dangerous/disruptive

	// SKIPPED: Test DeleteTemplate - action is dangerous/disruptive

	// SKIPPED: Test Groups - action is dangerous/disruptive

	// SKIPPED: Test RemoveGroup - action is dangerous/disruptive

	// SKIPPED: Test RemoveGroupFromTemplate - action is dangerous/disruptive

	// SKIPPED: Test RemoveProjectCreatorFromTemplate - action is dangerous/disruptive

	// SKIPPED: Test RemoveUser - action is dangerous/disruptive

	// SKIPPED: Test RemoveUserFromTemplate - action is dangerous/disruptive

	// SKIPPED: Test SearchTemplates - action is dangerous/disruptive

	// SKIPPED: Test SetDefaultTemplate - action is dangerous/disruptive

	// SKIPPED: Test TemplateGroups - action is dangerous/disruptive

	// SKIPPED: Test TemplateUsers - action is dangerous/disruptive

	// SKIPPED: Test UpdateTemplate - action is dangerous/disruptive

	// SKIPPED: Test Users - action is dangerous/disruptive
})
