// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test Available - action is dangerous/disruptive

	// SKIPPED: Test CancelAll - action is dangerous/disruptive

	// SKIPPED: Test Download - action is dangerous/disruptive

	// SKIPPED: Test Install - action is dangerous/disruptive

	// SKIPPED: Test Installed - action is dangerous/disruptive

	// SKIPPED: Test Pending - action is dangerous/disruptive

	// SKIPPED: Test Uninstall - action is dangerous/disruptive

	// SKIPPED: Test Update - action is dangerous/disruptive

	// SKIPPED: Test Updates - action is dangerous/disruptive
})
