// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test BulkDelete - action is dangerous/disruptive

	// SKIPPED: Test Create - action is dangerous/disruptive

	// SKIPPED: Test Delete - action is dangerous/disruptive

	// SKIPPED: Test Search - action is dangerous/disruptive

	// SKIPPED: Test SearchMyProjects - action is dangerous/disruptive

	// SKIPPED: Test SearchMyScannableProjects - action is dangerous/disruptive

	// SKIPPED: Test UpdateDefaultVisibility - action is dangerous/disruptive

	// SKIPPED: Test UpdateKey - action is dangerous/disruptive

	// SKIPPED: Test UpdateVisibility - action is dangerous/disruptive
})
