// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	sonar "github.com/boxboxjason/sonarqube-client-go/sonar"
	ginkgo "github.com/onsi/ginkgo"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test Delete - action is dangerous/disruptive

	// SKIPPED: Test List - action is dangerous/disruptive

	// SKIPPED: Test Rename - action is dangerous/disruptive
	ginkgo.Describe("Test SetAutomaticDeletionProtection in api/project_branches", func() {
		ginkgo.It("Should be ok", func() {
			opt := &sonar.ProjectBranchesSetAutomaticDeletionProtectionOption{
				Branch:  "main",
				Project: "test-project",
				Value:   "true",
			}
			resp, err := client.ProjectBranches.SetAutomaticDeletionProtection(opt)
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(204))
			gomega.Expect(resp.ContentLength).To(gomega.Equal(int64(0)))
		})
	})
	ginkgo.Describe("Test SetMain in api/project_branches", func() {
		ginkgo.It("Should be ok", func() {
			opt := &sonar.ProjectBranchesSetMainOption{
				Branch:  "main",
				Project: "test-project",
			}
			resp, err := client.ProjectBranches.SetMain(opt)
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(204))
			gomega.Expect(resp.ContentLength).To(gomega.Equal(int64(0)))
		})
	})
})
