// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test CreateEvent - action is dangerous/disruptive

	// SKIPPED: Test Delete - action is dangerous/disruptive

	// SKIPPED: Test DeleteEvent - action is dangerous/disruptive

	// SKIPPED: Test Search - action is dangerous/disruptive

	// SKIPPED: Test UpdateEvent - required param has no test value
})
