// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test AddGroup - action is dangerous/disruptive

	// SKIPPED: Test AddUser - action is dangerous/disruptive

	// SKIPPED: Test Copy - action is dangerous/disruptive

	// SKIPPED: Test Create - action is dangerous/disruptive

	// SKIPPED: Test CreateCondition - action is dangerous/disruptive

	// SKIPPED: Test DeleteCondition - action is dangerous/disruptive

	// SKIPPED: Test Deselect - action is dangerous/disruptive

	// SKIPPED: Test Destroy - action is dangerous/disruptive

	// SKIPPED: Test GetByProject - action is dangerous/disruptive

	// SKIPPED: Test List - action is dangerous/disruptive

	// SKIPPED: Test ProjectStatus - action is dangerous/disruptive

	// SKIPPED: Test RemoveGroup - action is dangerous/disruptive

	// SKIPPED: Test RemoveUser - action is dangerous/disruptive

	// SKIPPED: Test Rename - action is dangerous/disruptive

	// SKIPPED: Test Search - action is dangerous/disruptive

	// SKIPPED: Test SearchGroups - action is dangerous/disruptive

	// SKIPPED: Test SearchUsers - action is dangerous/disruptive

	// SKIPPED: Test Select - action is dangerous/disruptive

	// SKIPPED: Test SetAsDefault - action is dangerous/disruptive

	// SKIPPED: Test Show - action is dangerous/disruptive

	// SKIPPED: Test UpdateCondition - action is dangerous/disruptive
})
