// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	ginkgo "github.com/onsi/ginkgo"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test ActivateRule - action is dangerous/disruptive

	// SKIPPED: Test ActivateRules - action is dangerous/disruptive

	// SKIPPED: Test AddGroup - action is dangerous/disruptive

	// SKIPPED: Test AddProject - action is dangerous/disruptive

	// SKIPPED: Test AddUser - action is dangerous/disruptive

	// SKIPPED: Test Backup - action is dangerous/disruptive

	// SKIPPED: Test ChangeParent - action is dangerous/disruptive

	// SKIPPED: Test Changelog - action is dangerous/disruptive

	// SKIPPED: Test Compare - action is dangerous/disruptive

	// SKIPPED: Test Copy - action is dangerous/disruptive

	// SKIPPED: Test Create - action is dangerous/disruptive

	// SKIPPED: Test DeactivateRule - action is dangerous/disruptive

	// SKIPPED: Test DeactivateRules - action is dangerous/disruptive

	// SKIPPED: Test Delete - action is dangerous/disruptive

	// SKIPPED: Test Export - action is dangerous/disruptive

	// SKIPPED: Test Exporters - action is dangerous/disruptive
	ginkgo.Describe("Test Importers in api/qualityprofiles", func() {
		ginkgo.It("Should be ok", func() {
			v, resp, err := client.Qualityprofiles.Importers()
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})

	// SKIPPED: Test Inheritance - action is dangerous/disruptive

	// SKIPPED: Test Projects - action is dangerous/disruptive

	// SKIPPED: Test RemoveGroup - action is dangerous/disruptive

	// SKIPPED: Test RemoveProject - action is dangerous/disruptive

	// SKIPPED: Test RemoveUser - action is dangerous/disruptive

	// SKIPPED: Test Rename - action is dangerous/disruptive

	// SKIPPED: Test Restore - action is dangerous/disruptive

	// SKIPPED: Test Search - action is dangerous/disruptive

	// SKIPPED: Test SearchGroups - action is dangerous/disruptive

	// SKIPPED: Test SearchUsers - action is dangerous/disruptive

	// SKIPPED: Test SetDefault - action is dangerous/disruptive

	// SKIPPED: Test Show - action is dangerous/disruptive
})
