// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test ChangeLogLevel - action is dangerous/disruptive

	// SKIPPED: Test DbMigrationStatus - action is dangerous/disruptive

	// SKIPPED: Test Health - action is dangerous/disruptive

	// SKIPPED: Test Info - action is dangerous/disruptive

	// SKIPPED: Test Liveness - action is dangerous/disruptive

	// SKIPPED: Test Logs - action is dangerous/disruptive

	// SKIPPED: Test MigrateDb - action is dangerous/disruptive

	// SKIPPED: Test Ping - action is dangerous/disruptive

	// SKIPPED: Test Restart - action is dangerous/disruptive

	// SKIPPED: Test Status - action is dangerous/disruptive

	// SKIPPED: Test Upgrades - action is dangerous/disruptive
})
