// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	"testing"
	"os"

	sonargo "github.com/boxboxjason/sonarqube-client-go/sonar"
	"github.com/onsi/ginkgo"
	"github.com/onsi/gomega"
)

var client *sonargo.Client
var _ = ginkgo.BeforeSuite(func() {
	sonarURL := os.Getenv("SONAR_URL")
	if sonarURL == "" {
		sonarURL = "http://127.0.0.1:9000"
	}
	c, err := sonargo.NewClient(sonarURL+"/api", "admin", "admin")
	gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
	client = c
	SetupTestResources(client)
})

func TestSonar(t *testing.T) {
	gomega.RegisterFailHandler(ginkgo.Fail)
	ginkgo.RunSpecs(t, "Sonar Suite")
}
