// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	ginkgo "github.com/onsi/ginkgo"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test CheckSecretKey - action is dangerous/disruptive

	// SKIPPED: Test Encrypt - action is dangerous/disruptive

	// SKIPPED: Test GenerateSecretKey - action is dangerous/disruptive

	// SKIPPED: Test ListDefinitions - action is dangerous/disruptive
	ginkgo.Describe("Test LoginMessage in api/settings", func() {
		ginkgo.It("Should be ok", func() {
			v, resp, err := client.Settings.LoginMessage()
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})

	// SKIPPED: Test Reset - action is dangerous/disruptive

	// SKIPPED: Test Set - action is dangerous/disruptive

	// SKIPPED: Test Values - action is dangerous/disruptive
})
