// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	"testing"
	"os"

	. "github.com/boxboxjason/sonarqube-client-go/sonar"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var client *Client
var _ = BeforeSuite(func() {
	sonarURL := os.Getenv("SONAR_URL")
	if sonarURL == "" {
		sonarURL = "http://127.0.0.1:9000"
	}
	c, err := NewClient(sonarURL+"/api", "admin", "admin")
	Expect(err).ShouldNot(HaveOccurred())
	client = c
	SetupTestResources(client)
})

func TestSonar(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Sonar Suite")
}
