// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import (
	sonar "github.com/boxboxjason/sonarqube-client-go/sonar"
	ginkgo "github.com/onsi/ginkgo"
	gomega "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test Anonymize - action is dangerous/disruptive

	// SKIPPED: Test ChangePassword - action is dangerous/disruptive

	// SKIPPED: Test Create - action is dangerous/disruptive

	// SKIPPED: Test Current - action is dangerous/disruptive

	// SKIPPED: Test Deactivate - action is dangerous/disruptive

	// SKIPPED: Test DismissNotice - action is dangerous/disruptive

	// SKIPPED: Test Groups - action is dangerous/disruptive

	// SKIPPED: Test IdentityProviders - action is dangerous/disruptive

	// SKIPPED: Test Search - action is dangerous/disruptive

	// SKIPPED: Test SetHomepage - action is dangerous/disruptive
	ginkgo.Describe("Test Update in api/users", func() {
		ginkgo.It("Should be ok", func() {
			opt := &sonar.UsersUpdateOption{
				Email: "test@example.com",
				Login: "test-user",
				Name:  "test-name",
			}
			v, resp, err := client.Users.Update(opt)
			gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
			gomega.Expect(resp.StatusCode).To(gomega.Equal(200))
			gomega.Expect(v).To(gomega.Not(gomega.BeNil()))
		})
	})

	// SKIPPED: Test UpdateIdentityProvider - action is dangerous/disruptive

	// SKIPPED: Test UpdateLogin - action is dangerous/disruptive
})
