// Code generated by `make generate`. DO NOT EDIT.

package sonargo_test

import ginkgo "github.com/onsi/ginkgo"

var _ = ginkgo.Describe("SonarCLI integration test", func() {
	ginkgo.BeforeEach(func() {})
	ginkgo.JustBeforeEach(func() {})

	// SKIPPED: Test Create - action is dangerous/disruptive

	// SKIPPED: Test Delete - action is dangerous/disruptive

	// SKIPPED: Test Deliveries - action is dangerous/disruptive

	// SKIPPED: Test Delivery - action is dangerous/disruptive

	// SKIPPED: Test List - action is dangerous/disruptive

	// SKIPPED: Test Update - action is dangerous/disruptive
})
